CREATE DATABASE IF NOT EXISTS taskboard
 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE taskboard;
CREATE TABLE tareas (
 id INT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(150) NOT NULL,
 estado VARCHAR(20) DEFAULT 'pendiente',
 urgente TINYINT(1) DEFAULT 0,
 fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE tableros (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE columnas (
 id INT AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(80) NOT NULL,
 orden INT DEFAULT 0,
 tablero_id INT NOT NULL,
 FOREIGN KEY (tablero_id) REFERENCES tableros(id)
 ON DELETE CASCADE
);
